# Generated by Django 5.0.4 on 2024-05-22 11:22

from django.db import migrations
from clean_text_rhoni import clean_text_snake_case


DATA = [
    {'name': 'contacto', 'label': 'Contacto'},
    {'name': 'contacto y esporas', 'label': 'Contacto y Esporas'},
    {'name': 'Transmisión aérea', 'label': 'Transmisión aérea'},
    {'name': 'Gotitas', 'label': 'Gotitas'},
    {'name': 'Entomológico', 'label': 'Entomológico'},
    {'name': 'Funcional', 'label': 'Funcional'},
    {'name': 'Preventivo', 'label': 'Preventivo'},
    {'name': 'Protector', 'label': 'Protector'},
    {'name': 'Oscuro', 'label': 'Oscuro'},
    {'name': 'no', 'label': 'No'},
]


model_name = 'PrecautionType'


def insert_data(apps, schema_editor):
    """Inserting dimensions"""
    model = apps.get_model('backend', model_name)
    for each_entry in DATA:
        isolation_name = each_entry.get('name')
        clean_entry = clean_text_snake_case(isolation_name)
        each_entry['name'] = clean_entry
        entry = model.objects.create(**each_entry)
        entry.save()

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_unaccent_postgres'),
    ]

    operations = [
        migrations.RunPython(insert_data)
    ]
