# Generated by Django 5.0.4 on 2024-05-22 11:22

from os import name
from django.db import migrations
from clean_text_rhoni import clean_text_snake_case


DATA = [
    {'name': 'contacto por esporas', 'label': 'Aislamiento de Contacto por Esporas'},
    {'name': 'contacto eareo', 'label': 'Aislamiento de Contacto Aéreo'},
    {'name': 'contacto por gotas', 'label': 'Aislamiento de Contacto por Gotas'},
    {'name': 'entomologico', 'label': 'Aislamiento Entomológico'},
    {'name': 'funcional', 'label': 'Aislamiento Funcional'},
    {'name': 'preventivo', 'label': 'Aislamiento Preventivo'},
    {'name': 'sin aislamiento', 'label': 'No'},
]

model_name = 'IsolationType'


def insert_data(apps, schema_editor):
    """Inserting dimensions"""
    model = apps.get_model('backend', model_name)
    for each_entry in DATA:
        isolation_name = each_entry.get('name')
        clean_entry = clean_text_snake_case(isolation_name)
        each_entry['name'] = clean_entry
        entry = model.objects.create(**each_entry)
        entry.save()

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_unaccent_postgres'),
    ]

    operations = [
        migrations.RunPython(insert_data)
    ]
