# Generated by Django 5.0.4 on 2024-05-22 11:22

from os import name
from django.db import migrations
from clean_text_rhoni import clean_text_snake_case


DATA = [
    {'name': 'monopersulfato', 'label': 'Monopersulfato de potasio 20%'},
    {'name': 'cloro', 'label': 'Cloro al 6%'},
    {'name': 'detergente', 'label': 'Detergente'},
    {'name': 'uv', 'label': 'Uso de UV'},
    {'name': 'soluciones cloradas alta concentración', 'label': 'soluciones cloradas alta concentración'},
]

model_name = 'CleaningType'


def insert_data(apps, schema_editor):
    """Inserting dimensions"""
    model = apps.get_model('backend', model_name)
    for each_entry in DATA:
        field_name = each_entry.get('name')
        clean_entry = clean_text_snake_case(field_name)
        each_entry['name'] = clean_entry
        entry = model.objects.create(**each_entry)
        entry.save()

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_precaution_type'),
    ]

    operations = [
        migrations.RunPython(insert_data)
    ]
