# Generated by Django 5.0.4 on 2024-05-22 13:06

from django.db import migrations
# Generated by Django 5.0.4 on 2024-05-22 11:22

from django.db import migrations
from clean_text_rhoni import clean_text_snake_case


DATA = [
    {'name': 'days', 'label': 'Días'},
    {'name': 'weeks', 'label': 'Semanas'},
    {'name': 'months', 'label': 'Meses'},
    {'name': 'years', 'label': 'Años'},
    {'name': 'medical_discharge', 'label': 'Alta Médica'},
    {'name': 'death', 'label': 'Muerte'},
    {'name': 'no', 'label': 'No'},
]

model_name = 'UnitsOfTime'


def insert_data(apps, schema_editor):
    """Inserting dimensions"""
    model = apps.get_model('backend', model_name)
    for each_entry in DATA:
        isolation_name = each_entry.get('name')
        clean_entry = clean_text_snake_case(isolation_name)
        each_entry['name'] = clean_entry
        entry = model.objects.create(**each_entry)
        entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_cleaning_type'),
    ]

    operations = [
        migrations.RunPython(insert_data)
    ]
