# Generated by Django 5.0.4 on 2024-05-22 14:32

from django.db import migrations
from clean_text_rhoni import clean_text_snake_case


DATA = [
    {'label': 'Higiene de manos con agua y jabón( no usar soluciones hidroalcohólicas)'},
    {'label': 'Uso de alcohol no destruye esporas'},
    {'label': 'Uso obligatorio de N95'},
    {'label': 'lavado de manos con agua y jabón'},
    {'label': 'Establecer origen, no se transmiten de persona a persona'},
]

model_name = 'IsolationWarnings'


def insert_data(apps, schema_editor):
    """Inserting dimensions"""
    model = apps.get_model('backend', model_name)
    for each_entry in DATA:
        isolation_label = each_entry.get('label')
        isolation_name = clean_text_snake_case(isolation_label)
        each_entry['name'] = isolation_name
        entry = model.objects.create(**each_entry)
        entry.save()

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_special_cases_isolation_time'),
    ]

    operations = [
        migrations.RunPython(insert_data)
    ]
