# Generated by Django 5.0.4 on 2024-05-22 14:57

from django.db import migrations
from clean_text_rhoni import clean_text_snake_case


DATA = [
    {'name': 'virus', 'label': 'Virus'},
    {'name': 'resistencia Bacteria', 'label': 'resistencia Bacteria'},
    {'name': 'Parasito', 'label': 'Parasito'},
    {'name': 'bacteria', 'label': 'bacteria'},
]

model_name = 'DiseaseType'


def insert_data(apps, schema_editor):
    """Inserting dimensions"""
    model = apps.get_model('backend', model_name)
    for each_entry in DATA:
        isolation_name = each_entry.get('name')
        clean_entry = clean_text_snake_case(isolation_name)
        each_entry['name'] = clean_entry
        entry = model.objects.create(**each_entry)
        entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_isolation_warnings'),
    ]

    operations = [
        migrations.RunPython(insert_data)
    ]
