# Generated by Django 5.0.4 on 2024-05-23 12:24

from django.db import migrations
from clean_text_rhoni import clean_text_snake_case
from backend.data_loading.load_diseases_data import get_diseases_data
from backend.data_loading.add_disease_related_instances import AddDiseasesData


diseases_data = get_diseases_data()


model_name = 'Disease'


def insert_data(apps, schema_editor):
    """Inserting dimensions"""
    model = apps.get_model('backend', model_name)
    for each_row in diseases_data:

        utils_add_data = AddDiseasesData(apps=apps, row_data=each_row)
        utils_add_data.add_all_data_to_disease_data()
        
        disease_instance = utils_add_data.disease_instance_data

        entry = model.objects.create(**disease_instance)

        utils_add_data.add_cleaning_types_to_instance_data()
        cleaning_type_instances = utils_add_data.cleaning_type_instances
        if cleaning_type_instances is not None:
            entry.cleaning_type.add(*cleaning_type_instances)
        else:
            entry.cleaning_type.add(cleaning_type_instances)

        entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_disease_type'),
    ]

    operations = [
        migrations.RunPython(insert_data)
    ]
